export { default as ChatLayout } from './ChatLayout.vue'
export { default as ChatHeader } from './ChatHeader.vue'
export { default as ChatWelcome } from './ChatWelcome.vue'
export { default as ChatMessageList } from './ChatMessageList.vue'
export { default as ChatFooter } from './ChatFooter.vue'
export { default as ChatSender } from './ChatSender.vue'
export { default as ChatProvider } from '@/entry/TrChatProvider.vue'
export { useDefaultBubbleConfig } from './useDefaultBubbleConfig'
export { useSlotFilter } from './useSlotFilter'
export type { UseDefaultBubbleConfigOptions } from './useDefaultBubbleConfig'
export * from './page-regions'
