import {
  TinyBaseSelect,
  TinyButton,
  TinyInput,
  TinyModal,
  TinyNumeric,
  TinyOption,
  TinyPopconfirm,
  TinyRadio,
  TinyRadioGroup,
  TinySelect,
  TinySlider,
  TinySwitch,
  TinyTabItem,
  TinyTabs,
  TinyTooltip,
} from './tiny-vue'
import TinyNotify from '@opentiny/vue-notify'

export * from './tiny-vue'
export { TinyButton as Button, TinySwitch as Switch }
export { TinyNotify as Notify }

export default {
  BaseSelect: TinyBaseSelect,
  Button: TinyButton,
  Input: TinyInput,
  Modal: TinyModal,
  Notify: TinyNotify,
  Numeric: TinyNumeric,
  Option: TinyOption,
  Popconfirm: TinyPopconfirm,
  Radio: TinyRadio,
  RadioGroup: TinyRadioGroup,
  Select: TinySelect,
  Slider: TinySlider,
  Switch: TinySwitch,
  TabItem: TinyTabItem,
  Tabs: TinyTabs,
  Tooltip: TinyTooltip,
  TinyBaseSelect,
  TinyButton,
  TinyInput,
  TinyModal,
  TinyNotify,
  TinyNumeric,
  TinyOption,
  TinyPopconfirm,
  TinyRadio,
  TinyRadioGroup,
  TinySelect,
  TinySlider,
  TinySwitch,
  TinyTabItem,
  TinyTabs,
  TinyTooltip,
}
