export const layoutSelectors = {
  pageTitle: 'h2',
  root: '.tr-layout',
  body: '.tr-layout__body',
  leftAside: '.tr-layout__aside.tr-layout__aside--left',
  rightAside: '.tr-layout__aside.tr-layout__aside--right',
  header: '.tr-layout__header',
  main: '.tr-layout__main',
  scrollTarget: '[data-testid="layout-scroll-target"]',
  footer: '.tr-layout__footer',
  scrollbar: '.tr-layout-proxy-scrollbar',
  scrollbarThumb: '.tr-layout-proxy-scrollbar__thumb',
  surface: '.tr-layout',
  floatingDragBar: '.tr-layout__drag-bar',
  backdrop: '.tr-layout__backdrop',
  leftResizeTrigger: '.tr-layout__resize-trigger--left',
  rightResizeTrigger: '.tr-layout__resize-trigger--right',
  floatingResizeTriggerS: '.tr-layout__floating-resize-trigger--s',
  floatingResizeTriggerE: '.tr-layout__floating-resize-trigger--e',
  floatingResizeTriggerW: '.tr-layout__floating-resize-trigger--w',
  floatingResizeTriggerNE: '.tr-layout__floating-resize-trigger--ne',
  floatingResizeTriggerNW: '.tr-layout__floating-resize-trigger--nw',
  floatingResizeTriggerSE: '.tr-layout__floating-resize-trigger--se',
  floatingResizeTriggerSW: '.tr-layout__floating-resize-trigger--sw',
}
