export { default as TrChat } from './Chat.vue'
export { default as TrChatUI } from './ChatUI.vue'
export { useChatRuntimeAdapter } from './composables/useChatRuntimeAdapter'
export { useChatHistoryData, useChatHistoryItems } from './composables/useChatHistoryItems'

export type {
  ChatBubbleEventPayload,
  ChatBubbleView,
  ChatBubbleStateChangePayload,
  ChatBubbleListOptions,
  ChatBeforeSend,
  ChatBeforeSendContext,
  ChatBeforeSendResult,
  ChatBrandOptions,
  ChatConversation,
  ChatConversationView,
  ChatConversationInfo,
  ChatHistoryData,
  ChatHistoryGroup,
  ChatComposerRuntime,
  ChatComposerLayoutOptions,
  ChatCssSize,
  ChatHistoryOptions,
  ChatLabels,
  ChatLayoutOptions,
  ChatMcpView,
  ChatMcpServerView,
  ChatMcpToolMap,
  ChatMcpToolView,
  ChatModelView,
  ChatModelOptionView,
  ChatSenderView,
  ChatLeftAsideSlotProps,
  ChatRightAsideSlotProps,
  ChatLeftAsideContentSlotProps,
  ChatHistoryItemPrefixSlotProps,
  ChatSenderSlotProps,
  ChatSurfaceOptions,
  ChatUIData,
  ChatUIEmits,
  ChatUIOptions,
  ChatUIProps,
  ChatUISlots,
  ChatAsideOpenChangePayload,
  ChatHistoryActionPayload,
  ChatPromptClickPayload,
  ChatModelSelectPayload,
  ChatModelFeatureChangePayload,
  ChatModelReasoningEffortChangePayload,
  ChatMcpAddServerPayload,
  ChatMcpRemoveServerPayload,
  ChatMcpServerEnabledChangePayload,
  ChatMcpToolEnabledChangePayload,
  ChatMessageContent,
  ChatMessageItem,
  ChatMessagePart,
  ChatPromptsOptions,
  ChatRightAsideOptions,
  ChatProcessingState,
  ChatRequestState,
  ChatRuntime,
  ChatRuntimeActionErrorPayload,
  ChatRunConfig,
  ChatMcpRunConfig,
  ChatMcpRuntime,
  ChatMcpServerInfo,
  ChatMcpToolInfo,
  ChatMcpToolState,
  ChatModelOption,
  ChatBuiltInModelFeature,
  ChatAsideOptions,
  ChatWelcomeOptions,
  ChatWelcomeComposerPlacement,
  ChatSenderOptions,
  ChatModelRuntime,
  ChatRuntimeActions,
  ChatRunConfigReasoning,
  ChatSenderDefaultActions,
  ChatStructuredData,
  ChatStructuredDataItem,
  ChatSendPayload,
  ChatToolCall,
  ChatReadable,
  ChatWritable,
} from './types'

export type {
  LayoutFloatingDragDetail,
  LayoutFloatingOptions,
  LayoutFloatingResizeDetail,
  LayoutFloatingState,
} from '@opentiny/tiny-robot'

export type { UseChatRuntimeAdapterOptions } from './composables/useChatRuntimeAdapter'
export type {
  ChatHistoryDisplayData,
  ChatHistoryItem,
  UseChatHistoryDataOptions,
  UseChatHistoryItemsOptions,
} from './composables/useChatHistoryItems'
