name: 'CI: Build'

on:
  workflow_call:
    inputs:
      skip-playground:
        description: 'Skip playground build'
        type: boolean
        default: false

jobs:
  build-job:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i --no-frozen-lockfile

      - name: Build components
        run: pnpm build

      - name: Build docs
        run: pnpm -F docs build

      - name: Save PR number
        if: github.event_name == 'pull_request'
        run: echo "${{ github.event.number }}" > pr_number.txt

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.event.pull_request.head.sha || github.sha }}
          path: |
            packages/components/dist
            packages/kit/dist
            packages/svgs/dist
            docs/dist
            pr_number.txt
          retention-days: 1
